### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by cihad** [TalhaK15/LinkedIn-Clone#2]
Site henuz responsive olarak gorunmuyor. Bence mobil uyumlu olmasi lazim.

**Comment by talhabw** [comment]
@cihad daha fazla ayrinti verebilir misin?

**Comment by cihad** [comment]
simdi soyle olacak telefonda tablette ve diger kucuk ekranlarda siteye girince sayfanin ekranin sinirlarindan tasmamasi lazim. bunu html ve css ozelliklerini kullanarak yapabilirsiniz. bkz google resposive.

**Comment by cihad** [comment]
Henüz responsive olmuş görünmüyor. Deneme girişiydi heralde. Tekrar açıyorum.

**Comment by talhabw** [comment]
@cihad Cache yüzünden sitenin eski halini görüntülüyor olabilirsin. Bende nasıl gördündüğüne dair [buraya](https://github.com/TalhaK15/LinkedIn-Clone/blob/master/video/site.mp4) bir video yükledim.

**Comment by cihad** [comment]
Siteye bakmadım. Bu issue kapattığın commit'e sadece tek satır değiştirmişsin görünüyor. Üstteki 
bağlantıdan görebilirsin ([e13b605](https://github.com/TalhaK15/LinkedIn-Clone/commit/e13b605e62fe791d59186912e8a911787d797e65))

**Comment by talhabw** [comment]
ha evet. bir kaç gündür uğraşıyorum belli bir şey yapınca github'a yüklüyorum. bu issue'yi kapatmayı unutmuşum. Küçük bir şey değiştirip onunla issue'yi kapatmıştım

**Comment by cihad** [comment]
@TalhaK15 aslinda burada responsive icin yaptigin butun degisiklikleri buraya eklemen iyi olur. Tabi responsive ozelligi bizim bu projede kucuk bir ozellik olabilir. Ama cogu site icin ugrasilmasi, uzerinde dusunulmesi gereken bir ozelliktir.

Simdi bundan sonra yaptigin butun degisiklikleri farkli bir branch altinda mesela 'responsive' branch'i altinda gelistir. Sonra buraya pull request yap. En dogru yol ne bilmiyorum. Yani belki de pull request yapmadan actigin branch'i master branch'i ile birlestirirken bu issue'yi kapatabilirsin. Arastirmasi bedava...

**Comment by talhabw** [comment]
#3

**Comment by cihad** [comment]
tamam harika olmus teşekkürler.
